### ISSUE TITLE
reshape error

### ISSUE THREAD

**Issue by elesun2018** [IDKiro/typhoon-baseline#1]
ValueError: cannot reshape array of size 2544320 into shape (1999,1999)
![image](https://user-images.githubusercontent.com/37207093/63575213-18140700-c5bc-11e9-843f-f72cef643be4.png)
thanks!

**Comment by IDKiro** [comment]
check the loaded data.
for python2:
```
print data2.shape
```
i write the code in python3, and i recommend you use python3 too.
try your best, i can't help you more.
